title: JPA example
description: JPA and MapStruct usage example
author:
  name: Romanow Alexey
  email: romanowalex@mail.ru

show_downloads: false
remote_theme: jekyll/minima
header_pages: ['']

minima:
  skin: classic
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/company/it-enduro" }
    - { platform: telegram, user_url: "https://t.me/romanowalex" }
    - { platform: youtube, user_url: "https://www.youtube.com/@it_enduro" }
