server:
  port: 8080

spring:
  application:
    name: jpa-example
  profiles:
    active: local
  config:
    import: optional:git.properties
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoint:
    health.probes.enabled: true
  endpoints:
    web:
      base-path: /manage
      exposure.include: info,health,loggers,prometheus
  metrics.tags:
    application: ${spring.application.name}
  health.diskspace.enabled: false
  endpoint.health.show-details: always
  info.git.mode: simple
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
